// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzsNtioI3QGEIf6TqVqxXpTvVF9XfxqE',
    appId: '1:279104476962:web:b02da523181c9d0f1fb77b',
    messagingSenderId: '279104476962',
    projectId: 'soul-trip-48208',
    authDomain: 'soul-trip-48208.firebaseapp.com',
    storageBucket: 'soul-trip-48208.firebasestorage.app',
    measurementId: 'G-TRSFMB96NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzMGgSMPnDVuo8CL-hCTATWACS9l0vgYY',
    appId: '1:279104476962:android:4404de4ef7d63a7b1fb77b',
    messagingSenderId: '279104476962',
    projectId: 'soul-trip-48208',
    storageBucket: 'soul-trip-48208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdqBYGvwsxa3fsApdr4VJAaBh1SWYY3-M',
    appId: '1:279104476962:ios:c2f5255707d19fc21fb77b',
    messagingSenderId: '279104476962',
    projectId: 'soul-trip-48208',
    storageBucket: 'soul-trip-48208.firebasestorage.app',
    iosBundleId: 'com.example.soulTrip',
  );
}
